# generated by datamodel-codegen:
#   filename:  gcp-datastore-interface-api.yaml
#   timestamp: 2024-04-25T16:01:46+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

class DatastoreEntityRequest(BaseModel):
    datastore_key: Optional[str] = Field(None, example='192837465')


class DatastoreEntityMultipleRequest(BaseModel):
    datastore_key: Optional[str] = Field(None, example='192837465')


class DatastoreEntityResponse(BaseModel):
    json_string_response_entity: Optional[str] = Field(
        None, example="{'id': 'x', 'insertion_timestamp': ' 2024-04-25T11:11:55Z'}"
    )


class DatastoreEntityMultipleResponse(BaseModel):
    __root__: List[Dict[str, Any]]


class ErrorResponse(BaseModel):
    exception: str = Field(..., description='exception')
    error_class: Optional[str] = Field(None, description='error message')
