version: '3.7'
services:
  gcp-datastore-lookup-api-dev:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    container_name: gcp-datastore-lookup-api-dev
    environment:
      - GCP_PROJECT_ID=dummy-project
      - GOOGLE_APPLICATION_CREDENTIALS=/home/appuser/.config/gcloud/application_default_credentials.json
      - PORT=8000
      - PYTHONPATH=/home/appuser/src:/home/appuser/tests
      - ENABLE_DOCS=true
    ports:
      - "8003:8000"
    volumes:
      - ./src:/home/appuser/src
      - ./tests:/home/appuser/tests
      - ~/.config/gcloud/application_default_credentials.json:/home/appuser/.config/gcloud/application_default_credentials.json
    depends_on:
      datastore:
        condition: service_healthy  # Wait until Datastore emulator is up and running

  datastore:
    image: google/cloud-sdk
    environment:
      - GCP_PROJECT_ID=dummy-project
    command: [ "sh", "-c", "gcloud beta emulators datastore start --project=$$GCP_PROJECT_ID --host-port=0.0.0.0:9000 --consistency=1.0 --no-store-on-disk" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

