steps:
  - name: gcr.io/cloud-builders/docker
    id: build-dev
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo 'export _IMAGE="europe-west2-docker.pkg.dev/${PROJECT_ID}/${_PRODUCT_NAME}-${_RUN_SERVICE_NAME}/${_RUN_SERVICE_NAME}"' >> $_BUILD_VARS
        source $_BUILD_VARS
        docker build . --target dev -t vm-dataservices/${_RUN_SERVICE_NAME}-dev
  - name: eu.gcr.io/$PROJECT_ID/devops/docker-compose
    id: docker-compose-up
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        source $_BUILD_VARS
        docker-compose -f docker-compose.yml up -d
  - name: gcr.io/cloud-builders/docker
    id: unit-tests
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        source $_BUILD_VARS
        docker exec gcp-cloud-run-template-api-dev /bin/sh -c "poetry run pytest /home/appuser/tests/unit_tests/"
  - name: gcr.io/cloud-builders/docker
    id: integration-tests
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        source $_BUILD_VARS
        docker exec gcp-cloud-run-template-api-dev /bin/sh -c "poetry run pytest /home/appuser/tests/integration_tests/"
  - name: gcr.io/cloud-builders/docker
    id: build-prod
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo 'export _IMAGE="europe-west2-docker.pkg.dev/${PROJECT_ID}/${_PRODUCT_NAME}-${_RUN_SERVICE_NAME}/${_RUN_SERVICE_NAME}"' >> $_BUILD_VARS
        source $_BUILD_VARS
        docker build . --target prod -t $$_IMAGE:latest -t $$_IMAGE:$TAG_NAME --cache-from vm-dataservices/${_RUN_SERVICE_NAME}-dev
options:
    pool:
      name: 'projects/prj-vo-analytics-n-dss-dev/locations/europe-west2/workerPools/worker-pool-dev'
images:
  - 'europe-west2-docker.pkg.dev/${PROJECT_ID}/${_PRODUCT_NAME}-${_RUN_SERVICE_NAME}/${_RUN_SERVICE_NAME}:$TAG_NAME'
  - 'europe-west2-docker.pkg.dev/${PROJECT_ID}/${_PRODUCT_NAME}-${_RUN_SERVICE_NAME}/${_RUN_SERVICE_NAME}:latest'
substitutions:
    _PRODUCT_NAME: unset
    _RUN_SERVICE_NAME: unset
    _BUILD_VARS: /workspace/build_vars
logsBucket: 'gs://${PROJECT_ID}_cloudbuild_logs'
timeout: 21600s
